### ISSUE TITLE
MS1 user Stories

### ISSUE THREAD

**Issue by gabidi** [gabidi/bismuth-web-wallet#1]
# Bismuth Online Wallet User stories
  This document outlines high level stories for version 1 of the Bismuth Online Wallet (BOW).
  Sarah and John are two fictional characters used in this document to describe how a typical BOW user would interact with the wallet and their expectations. This will help us determine the actual work needed (Work tickets) to get this done.
  
- Sarah: Represents a typical logged in (creates wallet) user. She uses her desktop that has a modern browser on it.
- John: Represents a typical 'non logged in' user. John is a 100% mobile user.
  
  ## Abbreviations used
  BIS = Bismuth
  PBK = Public Key
  PRK = Private Key
  
  # Wallet User Stories  
  
  ### When John goes to the BOW he should be able to enter his BIS PBK , click a button to quickly see a dashboard that highlights his   latest transactions, his balance (non logged in view). 
  
  ### Sarah can go to the BOW using a modern desktop browser and create a brand new account (PBK,PRK). When she does so , she will be r  eminded that the details of the account are private to her and that she MUST save this information in a safe place in order to be abl  e to use this account and any funds attached to it again. She will also be provided with an option to export this information to a fi  le (probably JSON) and print a paper wallet if she wants (QR codes for PBK/PRK)
  
  ### After creating an account, Sarah comes back to the BOW site and clicks the login button. She will be promoted with the following login choices:
- Enter her PBK/PRK combination via text box
- Use the previously generated text file to quickly login.
Once logged in she will will be able to see a dashboard displaying highlights of latest transactions, balance and also a dialog to tr  ansfer BIS from one address to another.

  ### John has just finished a job for Sarah and was paid in BIS , he can't wait to get paid so he goes to BOW and enters the transacti  on ID given to him by Sarah and can see the latest updates on his transaction. He is happy to know that the screen refreshes the data   every 30 (?) seconds and he doesn't have to keep tapping the tiny refresh button on his cell phone.

**Comment by EggPool** [comment]
Kim is new to Bismuth.
He wants to mine it quick and needs an address.

He goes to BOW and select "create a new wallet".
He can either generate the seed from random data (moving the mouse) or from a BIP-39 passphrase (24 words)
A password is also required in any case. A strong password is advised, but Kim can use what he wants.
Once this is done, he gets the usual warnings that he is sole responsible of his wallet, and get the option to download the wallet file (wallet.der) for storage/backup.
The wallet is also stored - in encrypted form, with the password in Kim's browser so he will find it when he comes back later.

Kim is now the happy owner of a brand new Bismuth address he can copy and paste into his miner.

note: local storage in the browser may be optional. load from file (wallet.der) and store in memory only may be enough for v1. To be discussed
note: BIP39 passphrase is in testing. Would make it easier to export wallets (PK) via qrcode.
